name: 15m update

on:
  schedule:
    - cron: '55/15 * * * *'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Check External IP
        run: |
          echo "External IP Address:"
          curl -s ifconfig.me
          echo ""

      - name: Install MySQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client

      - name: Test MySQL Connection
        run: |
          echo "Testing MySQL connection..."
          mysql -h ${{ secrets.DB_HOST }} \
               -P ${{ secrets.DB_PORT }} \
               -u ${{ secrets.DB_USER }} \
               -p${{ secrets.DB_PASS }} \
               -e "SELECT * FROM s1_login_log LIMIT 10;" 2>/dev/null || { echo "Failed to connect to MySQL"; exit 1; }
          echo "MySQL connection successful!"

      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install

      - name: Run sources
        env:
          NODE_OPTIONS: --max-old-space-size=8192 --experimental-json-modules
        run: |
          echo "Starting sources update..."
          npm run sources || exit 1
          echo "Sources update completed successfully"

      - name: Build project
        env:
          NODE_OPTIONS: --max-old-space-size=8192 --experimental-json-modules
        run: |
          echo "Starting build process..."
          npm run build || exit 1
          echo "Build completed successfully"

      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: build/
          server-dir: /public_html/spy.sander.wtf/
